[package]
name = "smol-serial-test"
version = "0.1.0"
authors = ["Brandon Edens <brandonedens@gmail.com>"]
edition = "2018"

[dependencies]
mio-serial = { version = "3.3.1", default-features = false }
smol = "0.1.18"
futures = "0.3.5"
